### ISSUE TITLE
Get the Text pronounce by the user

### ISSUE THREAD

**Issue by Zarukin** [capacitor-community/speech-recognition#12]
hello!
I tried to get the text that is pronounce by the user but with the promise of the function start i only get a reference to an Ljava.lang.Object  so i'm unable to use it.
Is-it a bug?

**Comment by Zarukin** [comment]
i found a way to make it work by replacing  in speech-recognition\android\src\main\java\com\getcapacitor\community\speechrecognition\SpeechRecognition.java line 163 by :  result.put("matches", matchesList != null ? new JSArray(matchesList.toArray()) : new JSArray());

**Comment by mrbatista** [comment]
@Zarukin which version you use?

**Comment by Zarukin** [comment]
the package is in 0.0.4

**Comment by mrbatista** [comment]
The master branch work with Android and iOS.
Will be release a new version shortly!

**Comment by Zarukin** [comment]
ok thanks for your help. I will keep an eye on it! :)

**Comment by mrbatista** [comment]
Before becoming a collaborator I had released my own version on npm.
If you want to try use this -> https://www.npmjs.com/package/@mrbatista/speech-recognition (it's the same code as this repository in the master branch)
