### ISSUE TITLE
unable send partial results in iOS

### ISSUE THREAD

**Issue by pvsantosh** [capacitor-community/speech-recognition#18]
**Describe the bug**
Even though i'm passing partialResults = true in the start() call, the plugin is not sending the partial results. Instead, it just sends one result to the angular code. 

**To Reproduce**
1. Add the plugin to the capacitor project
2. make an api call to the plugin
  SpeechRecognition.start({
        language: "en-US",
        maxResults: 2,
        prompt: "Say something",
        partialResults: true,
        popup: false,
      }).then((matches) => {
        this.micStatus = 'astro-listening';
        console.log(matches);
      })

**Expected behavior**
When the partialResults param is set to true, the plugin should send the intermediate results until it gets isFinal = true

**Smartphone (please complete the following information):**
 - Device: iPhone Simulator XS
 - OS: 13.3

**Comment by TobiTobsn007** [comment]
I have the same problem on iPhone 13 Pro iOS 15.1
Is there any solution already?

**Comment by riderx** [comment]
I did fix it in this PR https://github.com/capacitor-community/speech-recognition/pull/27
And published a version in case that not merged soon :)

**Comment by jcesarmobile** [comment]
closing since the linked PR was merged
