### ISSUE TITLE
Plugin doesn't work for Capacitor 3

### ISSUE THREAD

**Issue by NLueg** [capacitor-community/speech-recognition#19]
**Describe the bug**
Also with newly published version (1.0.0) doesn't work for Capacitor v3.

I created a PR that solves this issue: #16 

**Expected behavior**
It should be possible to build the app with the plugin 😄 

**Screenshots**
When I try to build I get the following compiling error:
![image](https://user-images.githubusercontent.com/48101693/130615556-3ca8f3b4-f121-4418-bd28-df73e45d1527.png)

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by mrbatista** [comment]
@NLueg released 2.0.0 version with support to Capacitor v3.
Thanks for the PR.
