### ISSUE TITLE
Android: Required permissions are not mentioned in the documentation

### ISSUE THREAD

**Issue by selcukbeyhan** [capacitor-community/speech-recognition#21]
Hello,
in the readme file, it doesn't speak of required permissions on Android platform.

thank you.

**Comment by mrbatista** [comment]
@selcukbeyhan Do you want to contribute to the project by adding them?

**Comment by DiogoParrinha** [comment]
For others that may need also help, I had to add in the manifest file:
```
  <queries>
    <intent>
      <action android:name="android.speech.RecognitionService" />
    </intent>
  </queries>
```

and of course:
```
  <uses-permission android:name="android.permission.RECORD_AUDIO" />
```
