### ISSUE TITLE
Android: the plugin is not working on targetSdkVersion >= 30 

### ISSUE THREAD

**Issue by aocou** [capacitor-community/speech-recognition#24]
**Is your feature request related to a problem? Please describe.**
The plugin works very well on targetSdkVersion = 29, but not working well on targetSdkVersion >= 30

**Describe the solution you'd like**
Having a stable version for targetSdkVersion >= 30
As per google:
Update your target API level by November 1, 2021
Starting November 1, 2021, updates to apps and games on Google Play will be required to target Android 11 (API level 30) or higher. After this date, you won't be able to upload new app bundles and APKs with a targetSdkVersion less than 30.

Configuring your app to target a recent API level ensures that users benefit from significant security and performance improvements, while still allowing your app to run on older Android versions (down to the minSdkVersion).

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by DiogoParrinha** [comment]
From my tests, everything seems to work fine with target 30

**Comment by csurbier** [comment]
I had same issue and found solution thanks to 
https://stackoverflow.com/questions/64319117/speechrecognizer-not-available-when-targeting-android-11

You need to add 

    <queries>
        <intent>
            <action android:name="android.speech.RecognitionService" />
        </intent>
    </queries>

to your manifest. Now the capacitor plugin works fine on targetSdkVersion >=30
