### ISSUE TITLE
Issue opening speak dialogue to listen voice

### ISSUE THREAD

**Issue by GISkarthick** [capacitor-community/speech-recognition#25]
Getting error in permission after setting all the installation and setup in mainactivity and android manifest. even after giving manual permission in app info , now getting the below error 

Unable to find a Capacitor plugin to handle requestCode, trying Cordova plugins 2002 , capture voice data is not returning to html.

couldn't get solution anywhere. am working as React PWA capacitor 3.

**Comment by jcesarmobile** [comment]
can you provide a sample app?

**Comment by jcesarmobile** [comment]
closing since there was no response
