### ISSUE TITLE
Does this plugin even work?

### ISSUE THREAD

**Issue by Artkoch** [capacitor-community/speech-recognition#3]
**Describe the bug**
After installation SpeechRecognition.available() throws error SpeechRecognition.available() is not a function
 
**Smartphone (please complete the following information):**
 - Device: [iPhone5]
 - OS: [e.g. iOS12.4.4]
 - Browser [Ionic Capacitor]

**Comment by reyco1** [comment]
Im having the same issue.... Works great on Android but in iOS I get the same results as you. Is this being looked in to?

**Comment by luckyboykg** [comment]
We need the owner of this plugin to publish a new version on npm.
Currently, We can go with the forked plugin from @mrbatista at this Url: https://www.npmjs.com/package/@mrbatista/speech-recognition.

`npm i @mrbatista/speech-recognition`

Usage on Angular with Capacitor 3:
`import { SpeechRecognition } from '@mrbatista/speech-recognition';`

**Comment by NLueg** [comment]
@luckyboykg awesome, thank you!

**Comment by selcukbeyhan** [comment]
I have a very similar issue too: `SpeechRecognition.hasPermission is not a function.`.

**Comment by mrbatista** [comment]
release v1.0.0 to npm
