### ISSUE TITLE
iOS - stop method does not check if audio engine is nill

### ISSUE THREAD

**Issue by DiogoParrinha** [capacitor-community/speech-recognition#30]
**Describe the bug**
If for some reason we need to stop the recording without actually knowing whether we're recording anything (i.e. we may want to shutdown something), the stop method will throw an exception and crash the app on iOS. On Android there's a try catch so this won't crash the app:
```
  @PluginMethod
  public void stop(final PluginCall call) {
    try {
      stopListening();
    } catch (Exception ex) {
      call.reject(ex.getLocalizedMessage());
    }
  }
```

The stop method should not assume that the optional is not null.

**To Reproduce**
1. Add code to request permissions, etc.
2. Go to your device settings and deny permissions for speech recognition and voice recording.
3. Add some method to force stop recognition - let's suppose that part of the code does not have context on whether something is recording but you want to perform some kind of component shutdown externally and want to force the resource stop.
4. The app will crash.

**Expected behavior**
The stop method should support this kind of scenario and not crash. We may get a logged exception, sure, but not crash the app.

```
    @objc func stop(_ call: CAPPluginCall) {
        DispatchQueue.global(qos: DispatchQoS.QoSClass.default).async {
            if self.audioEngine!.isRunning {
                self.audioEngine?.stop()
                self.recognitionRequest?.endAudio()
            }

            call.resolve()
        }
    }
```

since audioEngine is not checked for nill, it will just crash.

**Comment by JulienLecoq** [comment]
I have the same issue :/

**Comment by JulienLecoq** [comment]
Unfortunately, it seems that the plugin isn't really maintained anymore.
