### ISSUE TITLE
Add method to open app settings to change permissions

### ISSUE THREAD

**Issue by DiogoParrinha** [capacitor-community/speech-recognition#32]
**Is your feature request related to a problem? Please describe.**
If the user has no granted permissions, we may want to prompt the user to go to the app settings (see https://github.com/capacitor-community/barcode-scanner).

This is useful in situations where the user has denied permissions and now clicks the "microphone" button for example and we want to tell the user that he needs to change the permissions.

This should be fairly easy to do. See these examples:
- iOS: https://github.com/capacitor-community/barcode-scanner/blob/main/ios/Plugin/Plugin.swift#L434
- Android: https://github.com/capacitor-community/barcode-scanner/blob/main/android/src/main/java/com/dutchconcepts/capacitor/barcodescanner/BarcodeScanner.java#L483

**Describe the solution you'd like**
Method to open app settings.

**Describe alternatives you've considered**
Right now we need to tell the user to manually go there.

**Additional context**
N/A

**Comment by jcesarmobile** [comment]
The links are now broken.
Anyway, I don't think this is something all the plugins should include, but instead there should be a specific plugin that allows to go to the settings.
If every plugin that has permissions includes this, all the plugins will have duplicated code for the same feature.
