### ISSUE TITLE
Capacitor v4 support

### ISSUE THREAD

**Issue by NLueg** [capacitor-community/speech-recognition#36]
**Is your feature request related to a problem? Please describe.**

Capacitor v4 has been released and it would be great for this plugin to support v4.
There already is a PR for this: #35 

**Describe the solution you'd like**
Merge of the PR 😃

**Comment by jcesarmobile** [comment]
closing as https://github.com/capacitor-community/speech-recognition/pull/35 has been merged

it has been available on `next` npm tag for a while now
