### ISSUE TITLE
Add a feature that allows to listen to a given voice

### ISSUE THREAD

**Issue by JulienLecoq** [capacitor-community/speech-recognition#37]
**Is your feature request related to a problem? Please describe.**
I want to have speech recognition to have a command like pattern with an IoT device.
My app sends commands to the IoT device depending on the speech recognition.
But the speech recognition should only work to the owner of the smartphone that has the app installed on.

**Describe the solution you'd like**
The solution should be able to work offline (if possible). I don't want the smartphone to do internet requests, since I don't want to wait for the response to come back. I don't know enough AI, but I guess the expected solution would be to have an AI model that the user can train "quickly" and then, a specific function or some options passed to the start() method of SpeechRecognition should be able to recognize only the user voice thanks to the model trained.

**Describe alternatives you've considered**
Displaying a one-time code on the user app that the user should say for each voice command in order to authenticate its request. Arg, that's really not user friendly.

**Comment by JulienLecoq** [comment]
The feature could use that: https://github.com/alphacep/vosk-api (but does not seems to work for me rn)

**Comment by jcesarmobile** [comment]
This plugin uses the SDKs provided by Apple and Google as part of the OS, which don't have that feature.
There are no plans on integrating 3rd party speech recognition SDKs
