### ISSUE TITLE
SpeechRecognizer: not connected to the recognition service

### ISSUE THREAD

**Issue by Sharcoux** [capacitor-community/speech-recognition#38]
**Describe the bug**
SpeechRecognizer doesn't work on Android. The logcat shows the following error: `SpeechRecognizer: not connected to the recognition service`. This is triggered immediately when calling `start`. No results are showing up after that.

Tested version: 3.6.0

**To Reproduce**
1. Add `import { SpeechRecognition } from '@capacitor-community/speech-recognition'` to your project
2. Call:
 ```
SpeechRecognition.start({
      language: 'en-US',
      maxResults: undefined,
      partialResults: true,
      popup: false,
    })
```
3. Open the logcat
4. No results, console logs `Client side error`, and logcat shows `SpeechRecognizer: not connected to the recognition service`

**Expected behavior**
If adding a listener to partialResults, should show the results

**Smartphone (please complete the following information):**
 - OS: [e.g. iOS8.1] Android
 - Version [e.g. 22] 12

**Comment by JulienLecoq** [comment]
I get the same error ``SpeechRecognizer: not connected to the recognition service`` if I start, stop and restart the plugin but I still get results haha (I'm using partialResults = true)

**Comment by Sharcoux** [comment]
Unfortunately, I'm not that lucky... :disappointed:

**Comment by Sharcoux** [comment]
With a deeper understanding on the issue, I'll try to open a more detail issue.

**Comment by soumaya871** [comment]
I have the same error how did you solve this problem please

**Comment by dlee** [comment]
I get the same error:
```
Beginning to listen for audible speech
not connected to the recognition service
File: http://localhost/ - Line 281 - Msg: undefined
Sending plugin error: {"save":false,"callbackId":"85171282","pluginId":"SpeechRecognition","methodName":"start","success":false,"error":{"message":"No match"}}
Sending plugin error: {"save":false,"callbackId":"85171282","pluginId":"SpeechRecognition","methodName":"start","success":false,"error":{"message":"Client side error"}}

**Comment by marckevinflores** [comment]
I got the same issue, is there anyone can solve this issue? I use `"@capacitor-community/speech-recognition": "^5.0.0"`
