### ISSUE TITLE
addListener not firing.

### ISSUE THREAD

**Issue by radiodee1** [capacitor-community/speech-recognition#39]
**Describe the bug**
When my app runs I see a popup. I can speak to the popup and I see my text in the popup. Then the popup dissapears. My logcat does not have the statement "partialResults was fired". I guess my problem is with the "addListener" code. It does not seem to work.

**To Reproduce**
1. add speech-recognition 3 to package.json, npm install
2. npx cap sync
3. start app in emulator with mic on
4. popup takes audio input
5. js app does not show that input

**Expected behavior**
A line in logcat that has partialResults in it.

**Desktop (please complete the following information):**
 - OS: ubuntu 22.04
 - Browser: android emulator Pixel2 api 30

**Smartphone (please complete the following information):**
 - Device: emulator
 - OS: android

**Additional context**

I have a problem. My logcat says:

        D/Capacitor: Unable to find a Capacitor plugin to handle requestCode, trying Cordova plugins 2002

Here is some of my javascript:

      console.log("start record");
      SpeechRecognition.addListener("partialResults", (data) => {
        const data_matches = data.matches[0]; 
        console.log("partialResults was fired", data_matches);
        
      });
 
      const match = await SpeechRecognition.start({
        language: "en-US",
        maxResults: 1,
        prompt: "Say something",
        partialResults: false,
        popup: true,
      });

**Comment by jishnude** [comment]
Were you able to solve this problem. I am hitting the same issue

**Comment by Timutchin** [comment]
For OS Android use data.value instead of data.matches

**Comment by jcesarmobile** [comment]
On Android, partial results don't work if using popup as the popup takes the partial results for itself to show them in the popup.
I've added that information to the addListener types

Also fixed the return to use matches as iOS and types do instead of values.
