### ISSUE TITLE
Unclear documentation and feature request

### ISSUE THREAD

**Issue by DouglasLapsley** [capacitor-community/speech-recognition#4]
It's not clear how you get the text after detection.  

Please update the documentation with an example of how that would be implemented.

Also, is it possible to override Android cutting off the recording if it thinks the speech has finished?  I need to detect the text for a set period of time.  So maybe an extra RecognizerIntent constant could be passed into SpeechRecognition.start() for EXTRA_SPEECH_INPUT_MINIMUM_LENGTH_MILLIS and / or EXTRA_SPEECH_INPUT_COMPLETE_SILENCE_LENGTH_MILLIS per https://developer.android.com/reference/kotlin/android/speech/RecognizerIntent#EXTRA_SPEECH_INPUT_MINIMUM_LENGTH_MILLIS:kotlin.String

Thanks

**Comment by tansah** [comment]
I suppose this plugin is no longer maintained.. is it? I saw on other similar plugin, you need to do a .subscribe, after you .start, however when i try, it doesnt work..

**Comment by mrbatista** [comment]
released version v1.0.0 to npm
