### ISSUE TITLE
Add function to remove listeners

### ISSUE THREAD

**Issue by saricden** [capacitor-community/speech-recognition#40]
**Is your feature request related to a problem? Please describe.**
Right now, as far as I can tell, there is no way to unbind an event listener once it's bound. This raises problems with the new `useEffect` architecture in ReactJS when an empty dependency array is passed. The new behaviour is such that the `useEffect` callback triggers twice on a component mount. It is common practice to bind to events, but unbind in the callback's return function. However as far as I can tell, this is currently not possible with this library.

**Describe the solution you'd like**
A simple `removeListener(string eventName, Function callback)`, or even a `removeAllListeners()` function would be perfect. Pretty self-explanatory.

**Describe alternatives you've considered**
For my React-specific implementation, I've for now setup a double `useEffect` which sets a boolean to trigger a second useEffect, when mounted, causing the second `useEffect`'s callback to only trigger once. I'm happy to describe this in more detail, but I do think a `removeListener` method would lend itself well to other situations as well as my simple React case.

**Additional context**
N/a, I think it's all summed up above ☝️

**Comment by saricden** [comment]
PS, if I can balance it with my work and other commitments, I'd be happy to attempt a PR for this. Let me know if you'd like me to take a stab at it 😄

**Comment by jcesarmobile** [comment]
All Capacitor plugins return a handler on addListener that can be used to remove the listener you just added.

```
let handler = await SpeechRecognition.addListener("partialResults", (data: any) => {
  console.log("partialResults was fired", data.matches);
});
handler.remove();
```

But I've added removeAllListeners method to match other Capacitor plugins.
