### ISSUE TITLE
Release new version with ios implementation

### ISSUE THREAD

**Issue by mrbatista** [capacitor-community/speech-recognition#5]
**Describe the bug**
The master branch has ios implementation but the latest release (0.0.4) implement only android platform.

**Comment by blackdtools** [comment]
I can confirm this is still happening and it is a critical issue for any user that want support for iOS...
Please just launch a new release from master asap.


Current content of Plugin.swift in the latest release (0.0.4) 
`import Foundation
import Capacitor

/**
 * Please read the Capacitor iOS Plugin Development Guide
 * here: https://capacitor.ionicframework.com/docs/plugins/ios
 */
@objc(SpeechRecognition)
public class SpeechRecognition: CAPPlugin {
    
    @objc func echo(_ call: CAPPluginCall) {
        let value = call.getString("value") ?? ""
        call.success([
            "value": value
        ])
    }
}
`
That is: the default content for a new Plugin. I believe it is a mistake.

**Comment by NLueg** [comment]
@priyankpat could you please publish a new version on npm with the fixes iOS-Implementation? The plugin isn't working otherwise.

**Comment by mrbatista** [comment]
released version v1.0.0 to npm
