### ISSUE TITLE
Partial Results listener does not fire on Android 13

### ISSUE THREAD

**Issue by anandsathe67** [capacitor-community/speech-recognition#61]
**Describe the bug**
On Android 13 (API 33), the partial results listener never fires. Could it be because of the changes mentioned here 
https://developer.android.com/about/versions/13/behavior-changes-all#speech-service
See also - https://stackoverflow.com/questions/73516849/how-to-get-devices-default-speechservice-provider-android-api-13 for a possible implementation using the default speech provider. 
**Expected behavior**
The partialResults listener should fire as it does on iOS

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: OPPO F74
 - OS: ColorOS 13.0 (Android 13)

**Additional context**
The plugin is pretty much unusable without the listener firing

**Comment by madruga8** [comment]
i tried with the permissions above and the partialResults event still dont fire...

**Comment by madruga8** [comment]
It didn't worked on APIs 33 and 32... I had to rollback do Cordova plugin that still working besides being updated 7 years ago...

**Comment by jcesarmobile** [comment]
Can you provide a sample app?
Seems to work fine for me.

The plugin adds the `<uses-permission android:name="android.permission.RECORD_AUDIO" />` permission, you don't have to add it yourself. But you have to request it with `SpeechRecognition.requestPermission();`.
That was added on version 4 of the plugin, so make sure you are in 4.0.0 or newer.

**Comment by jcesarmobile** [comment]
closing since there was no response.
I updated the plugin to use Capacitor 5 and the listener was working fine.
