### ISSUE TITLE
Api key required

### ISSUE THREAD

**Issue by CappelloNicola** [capacitor-community/speech-recognition#67]
**Describe the bug**
Not really a bug, I just need help. When the start function is executed, a toast notify that an api key is required and to check the log. The log states that it's impossible to connect to the service. I suppose it needs google speech recognition api key. If so, once I obtain the key, how do i use it? 

**Smartphone (please complete the following information):**
 - Device: [Honor 9]
 - OS: [Android 9]

**Comment by jcesarmobile** [comment]
The plugin doesn't require an API key, the speech recognition is supposed to be provided by the OS.

Most devices will rely on installed google apps for the speech recognition, but for Chinese vendors that don't include google apps, you might need additional setup. I can't find any information about what might be required for honor devices, try opening stock honor apps that might have speech recognition enabled and see if it popups something.
