### ISSUE TITLE
Event Listener for Final Result or Listening Stopped

### ISSUE THREAD

**Issue by alistairheath** [capacitor-community/speech-recognition#68]
**Is your feature request related to a problem? Please describe.**
On iOS and Android when implementing this plugin, speech recognitions starts and then stops either when the user finishes talking or after a predetermined a mount of time. Whilst it is possible to capture the partial results as the listener is talking. It doesn't seem possible to either listen indefinitely and the use the .stop() method to manually stop listening and process teh final result, nor is there a listener to return the full result.

**Describe the solution you'd like**
I think the above could be solved with one of two new features:
- An event listener for "finalResult" as well as "partialResult".
- The ability for the speech recognition to go on indefinitely with a manual .stop() ending it. This could be followed by a .then() which could handle the final results set.

**Describe alternatives you've considered**
- If details could be shared in the documentation for the default listening time on each platform then one could set a Timeout to trigger once listening has stopped.
- An isListening() method was proposed in Issue #44, this could be repeatedly called to determine if the listening session ahs ended, were this feature to be implemented.

**Comment by adamcohenhillel** [comment]
Is there an update on this one?

**Comment by focafull** [comment]
For me not having this events makes it unusable for now. Maybe an error event would be nice to have.

**Comment by veneliniliev** [comment]
I need this feature too! pleaseee @jcesarmobile

**Comment by shaibrown5** [comment]
for me IOS works fine, records on start and stops recording on stop.
however Android does not work. as stated above, the recording finishes when user pauses or after a few seconds. 

PR #83 added a useful isListening method that has 2 problems:
Ios - isListening returns undefined both when recording and not.
Android - isListening  works fine, but can not be used to override the automatic stopping of the recording.

**Comment by jcesarmobile** [comment]
isListening is working fine for me on iOS, if it doesn't work for you, please, create a new issue and provide a sample app that reproduces the problem

it's not possible to do continuous recognition on any of the platforms, iOS stops after a minute, Android when it detects a silence.
You can listen for the `listeningState` event and when the status is stopped call start again.

iOS was missing some cases where `listeningState` with stopped value should be fired, fixed on https://github.com/capacitor-community/speech-recognition/pull/95
