### ISSUE TITLE
Not recognize integer numbers from 1 to 9

### ISSUE THREAD

**Issue by sashko687** [capacitor-community/speech-recognition#77]
**Describe the bug**
On Android devices not recognize digits at all  or so very rarely.

**Expected behavior**
Should recognize integer numbers from 1 to 9

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy M21
 - OS: Android 12

**Comment by jcesarmobile** [comment]
Working fine for me, I guess it depends on the device and pronunciation.
Anyway, the plugin just wraps the native APIs, everything related to the actual recognition is developed by Apple/Google/Other Speech recognition provider, nothing we can do from the plugin to improve the results.
