### ISSUE TITLE
Pronunciation problem

### ISSUE THREAD

**Issue by iamandreadompe** [capacitor-community/speech-recognition#80]
**Describe the bug**
Hello the plugin works great but i've noticed an issue with my surname (Dompè), if i say "Dompè" i get Dom pe
with the space and the surname recognition process fails,
because it is pronounced within a longer sentence and therefore in these cases there is no possibility to understand the correct surname

**To Reproduce**
Pronounce "Dompè" in a sentence

**Expected behavior**
I would like to get the correct sentence and the word Dompè all attached

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS
 - Version 5.0.0

**Smartphone (please complete the following information):**
 - Device: iPhone11
 - OS: 17.2.1

**Additional context**
i use the language 'it-IT'

**Comment by jcesarmobile** [comment]
The plugin doesn't really do the recognition, that's done by the native APIs the plugin calls, you can report the issue to Apple, but I wouldn't expect speech recognizers to work well with surnames.
