### ISSUE TITLE
Bug: `checkPermission()" is wrongly delivering "prompt" when denied before.

### ISSUE THREAD

**Issue by gklasen** [capacitor-community/speech-recognition#88]
Hey, whenever i triggered `requestPermission()` in the Plugin and i decline it, `console.log(await SpeechRecognition.checkPermissions())` will deliver `speechRecognition: "prompt"`. Instead, it should be "denied", no?

Operating on Android 13.

**Comment by jcesarmobile** [comment]
`requestPermission()` is deprecated, the correct method is `requestPermissions()`.

On Android, when the permission is denied once, it still allows to request the permission again, in that case `checkPermissions()` returns `prompt-with-rationale`, meaning you should show the user some custom message explaining why the permission is important for your app to work before calling `requestPermissions()` again as it the user doesn't allow the permission the second time you won't be able to request it again.

I'm removing `requestPermission()` and `hasPermission()` in next major release to avoid the confusion.
