### ISSUE TITLE
Plugin does not work on ios

### ISSUE THREAD

**Issue by 1MaddieX** [capacitor-community/speech-recognition#9]
**Describe the bug**
 - When imported, the plugin does not work at all, I keep getting a `SpeechRecognition.available() is not a function`. This actually happens for *all* functions with this plugin

**To Reproduce**
 - Follow install instructions and import plugin

**Expected behavior**
 - Plugin functions as documented

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser N/A
 - Version [e.g. 11.1]

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 14.1
 - Browser CapacitorJS
 - Version 2.4.3

**Comment by ymmedia** [comment]
Hello , 
I think the ios implementation is not terminating the public methods are not declared in the file: speech-recognition / ios / Plugin / Plugin.m

**Comment by mrbatista** [comment]
@ymmedia Temporary workaround is to use my library https://www.npmjs.com/package/@mrbatista/speech-recognition
This contain the change of PR #8

**Comment by ymmedia** [comment]
👍

**Comment by dwieeb** [comment]
@mrbatista Apologies for the lack of response on your PR. Would you be able to join the [Capacitor Contributors slack](https://getcapacitor.herokuapp.com/)?

**Comment by r614** [comment]
@dwieeb any way can we get the PR merged?

**Comment by mrbatista** [comment]
PR #8 add support to ios
